window.OSTERMANN_BLOG_POSTS = [
  {
    id: "post-exames-normais",
    title: "Exames normais, mas os sintomas continuam: o que investigar?",
    slug: "exames-normais-mas-sintomas",
    excerpt: "Entenda por que sintomas reais podem persistir mesmo com exames normais e quais caminhos ajudam a investigar a causa raiz.",
    image: "../assets/images/IDOSO.png",
    imageAlt: "Medicina investigativa para pacientes com exames normais e sintomas persistentes",
    category: "Longevidade",
    tags: ["exames normais", "sintomas persistentes", "medicina investigativa", "causa raiz"],
    author: "Ostermann Medical Center",
    status: "published",
    publishedAt: "2026-06-16",
    updatedAt: "2026-06-16",
    readTime: 6,
    views: 980,
    featured: true,
    metaTitle: "Exames normais e sintomas: o que investigar?",
    metaDescription: "Exames normais e sintomas persistentes exigem investigação cuidadosa. Veja o que pode estar por trás do desconforto e quando buscar ajuda.",
    primaryKeyword: "exames normais e sintomas persistentes",
    secondaryKeywords: ["exames normais", "sintomas persistentes", "causa raiz", "medicina investigativa"],
    searchIntent: "Pessoa com sintomas sem explicação procurando uma investigação mais profunda.",
    url: "/blog/exames-normais-mas-sintomas",
    related: ["inchaco-abdominal-causas", "resistencia-insulinica-emagrecimento"],
    content: [
      "<p>Ter <strong>exames normais e sintomas persistentes</strong> pode ser frustrante. A pessoa sente cansaço, desconforto digestivo, dificuldade para emagrecer ou sono ruim, mas recebe a resposta de que está tudo bem.</p>",
      "<h2>Por que exames normais não encerram a investigação?</h2>",
      "<p>Exames de rotina são importantes, mas muitas vezes mostram apenas uma parte da história. Alterações metabólicas iniciais, inflamação silenciosa, desequilíbrios hormonais e problemas de absorção podem não aparecer em uma avaliação básica.</p>",
      "<h2>O que pode estar por trás dos sintomas?</h2>",
      "<p>Alguns sinais merecem uma leitura integrada: fadiga constante, intestino irregular, refluxo, ganho de peso sem explicação, compulsão alimentar, sono não reparador e perda de energia ao longo do dia.</p>",
      "<h3>Quando procurar uma avaliação mais profunda?</h3>",
      "<p>Quando os sintomas atrapalham a rotina e se repetem mesmo com exames sem grandes alterações, vale investigar marcadores complementares, histórico clínico, composição corporal, hábitos, sono e metabolismo.</p>",
      "<p>Leia também sobre <a href=\"/blog/inchaco-abdominal-causas\">inchaço abdominal e causas comuns</a> e sobre <a href=\"/blog/resistencia-insulinica-emagrecimento\">resistência insulínica no emagrecimento</a>.</p>"
    ],
    seoPlan: {
      theme: "Exames normais com sintomas persistentes",
      primaryKeyword: "exames normais e sintomas persistentes",
      secondaryKeywords: "exames normais, sintomas persistentes, causa raiz, medicina investigativa",
      intent: "Pessoa buscando uma explicação para sintomas que não aparecem em exames básicos",
      category: "Diagnóstico integrativo",
      seoTitle: "Exames normais e sintomas: o que investigar?",
      metaDescription: "Exames normais e sintomas persistentes exigem investigação cuidadosa. Veja o que pode estar por trás do desconforto e quando buscar ajuda.",
      suggestedUrl: "/blog/exames-normais-mas-sintomas"
    }
  },
  {
    id: "post-inchaco",
    title: "Inchaço abdominal constante: causas que você não deve ignorar",
    slug: "inchaco-abdominal-causas",
    excerpt: "Inchaço recorrente pode envolver digestão, microbiota, inflamação e intolerâncias. Veja sinais que merecem avaliação.",
    image: "../assets/images/BARRIGA.png",
    imageAlt: "Inchaço abdominal constante: causas e sinais de alerta",
    category: "Saúde Digestiva",
    tags: ["inchaço abdominal", "saúde digestiva", "intestino", "microbiota"],
    author: "Ostermann Medical Center",
    status: "published",
    publishedAt: "2026-06-16",
    updatedAt: "2026-06-16",
    readTime: 5,
    views: 760,
    featured: true,
    metaTitle: "Inchaço abdominal constante: principais causas",
    metaDescription: "Inchaço abdominal constante pode indicar alterações digestivas, microbiota desequilibrada ou inflamação. Entenda quando investigar.",
    primaryKeyword: "inchaço abdominal constante",
    secondaryKeywords: ["inchaço abdominal", "saúde digestiva", "intestino irregular", "microbiota"],
    searchIntent: "Pessoa com desconforto digestivo recorrente procurando causas e orientação.",
    url: "/blog/inchaco-abdominal-causas",
    related: ["exames-normais-mas-sintomas", "resistencia-insulinica-emagrecimento"],
    content: [
      "<p>O <strong>inchaço abdominal constante</strong> não deve ser visto apenas como um incômodo depois das refeições. Quando ele se repete, pode sinalizar que a digestão precisa ser investigada com mais cuidado.</p>",
      "<h2>Inchaço abdominal constante: possíveis causas</h2>",
      "<p>Entre as causas possíveis estão intolerâncias alimentares, alterações da microbiota, constipação, baixa capacidade digestiva, inflamação intestinal e consumo de alimentos que fermentam em excesso.</p>",
      "<h2>Quando o intestino interfere no metabolismo?</h2>",
      "<p>A saúde digestiva influencia energia, absorção de nutrientes, resposta inflamatória e até controle do peso. Por isso, tratar apenas o sintoma pode não resolver o problema.</p>",
      "<h3>Sinais de alerta para investigar</h3>",
      "<p>Procure avaliação se o inchaço aparece com dor, intestino irregular, refluxo, cansaço, perda de energia ou mudanças no peso.</p>",
      "<p>Para entender melhor o contexto, veja também <a href=\"/blog/exames-normais-mas-sintomas\">por que exames normais podem não explicar sintomas</a>.</p>"
    ],
    seoPlan: {
      theme: "Inchaço abdominal constante",
      primaryKeyword: "inchaço abdominal constante",
      secondaryKeywords: "inchaço abdominal, saúde digestiva, intestino irregular, microbiota",
      intent: "Pessoa buscando causas e soluções para desconforto digestivo recorrente",
      category: "Saúde digestiva",
      seoTitle: "Inchaço abdominal constante: principais causas",
      metaDescription: "Inchaço abdominal constante pode indicar alterações digestivas, microbiota desequilibrada ou inflamação. Entenda quando investigar.",
      suggestedUrl: "/blog/inchaco-abdominal-causas"
    }
  },
  {
    id: "post-insulina",
    title: "Resistência insulínica e emagrecimento: por que o peso não muda?",
    slug: "resistencia-insulinica-emagrecimento",
    excerpt: "A resistência insulínica pode dificultar o emagrecimento mesmo com dieta e exercício. Entenda o que investigar.",
    image: "../assets/images/INSULINA.png",
    imageAlt: "Resistência insulínica e dificuldade para emagrecer",
    category: "Metabolismo",
    tags: ["resistência insulínica", "emagrecimento", "metabolismo", "glicose"],
    author: "Ostermann Medical Center",
    status: "published",
    publishedAt: "2026-06-16",
    updatedAt: "2026-06-16",
    readTime: 6,
    views: 890,
    featured: true,
    metaTitle: "Resistência insulínica e emagrecimento",
    metaDescription: "Resistência insulínica e emagrecimento estão ligados. Veja por que o peso pode travar e quais sinais indicam investigação metabólica.",
    primaryKeyword: "resistência insulínica e emagrecimento",
    secondaryKeywords: ["resistência insulínica", "insulina", "emagrecimento", "metabolismo lento", "glicose"],
    searchIntent: "Pessoa tentando emagrecer e procurando explicações para peso estagnado.",
    url: "/blog/resistencia-insulinica-emagrecimento",
    related: ["exames-normais-mas-sintomas", "inchaco-abdominal-causas"],
    content: [
      "<p><strong>Resistência insulínica e emagrecimento</strong> estão diretamente ligados. Quando as células respondem mal à insulina, o corpo tende a armazenar mais energia e usar menos gordura como combustível.</p>",
      "<h2>Como a resistência insulínica atrapalha o emagrecimento?</h2>",
      "<p>Mesmo com redução calórica e exercícios, a pessoa pode sentir fome intensa, queda de energia, compulsão por doces e dificuldade para reduzir medidas.</p>",
      "<h2>Sinais que merecem investigação metabólica</h2>",
      "<p>Circunferência abdominal elevada, sonolência após comer, histórico familiar de diabetes, gordura no fígado e exames de glicose no limite podem indicar que o metabolismo precisa de uma leitura mais completa.</p>",
      "<h3>O que avaliar além do peso?</h3>",
      "<p>Composição corporal, glicemia, insulina, marcadores inflamatórios, sono, rotina alimentar e massa muscular ajudam a entender o que está travando o resultado.</p>",
      "<p>Veja também por que <a href=\"/blog/exames-normais-mas-sintomas\">exames normais podem não encerrar a investigação</a>.</p>"
    ],
    seoPlan: {
      theme: "Resistência insulínica e dificuldade para emagrecer",
      primaryKeyword: "resistência insulínica e emagrecimento",
      secondaryKeywords: "resistência insulínica, insulina, emagrecimento, metabolismo lento, glicose",
      intent: "Pessoa que tenta emagrecer e busca uma explicação metabólica para o peso travado",
      category: "Metabolismo",
      seoTitle: "Resistência insulínica e emagrecimento",
      metaDescription: "Resistência insulínica e emagrecimento estão ligados. Veja por que o peso pode travar e quais sinais indicam investigação metabólica.",
      suggestedUrl: "/blog/resistencia-insulinica-emagrecimento"
    }
  }
];
